# Generated by Django 2.2.5 on 2019-09-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
